'''
Created on 11-Sep-2014

@author: aravind
'''

from django.conf.urls import patterns, url
from journal_mgmt import views
from django.conf.urls.static import static

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^auto_pl_mgmt/$', views.auto_pl_mgmt, name='auto_pl_mgmt'),
    url(r'^auto_pl_mgmt/pl_bom_add/detail/id=(?P<pl_id>\d+)/$', views.bom_add_popup, name='bom_add_popup'),
    url(r'^auto_price_list/index/$', views.auto_price_list_index, name='auto_pl_index'),
    url(r'^auto_price_list/del_index/$', views.auto_price_list_del_index, name='auto_pl_del_index'),
    url(r'^auto_price_list/delete/id=(?P<auto_pl_id>\d+)/$', views.auto_price_list_delete, name='auto_price_list_delete'),
    url(r'^auto_price_list/detail/id=(?P<auto_pl_id>\d+)/$', views.auto_price_list_detail, name='auto_pl_detail'),
    url(r'^auto_price_list/update/id=(?P<auto_pl_id>\d+)/$', views.auto_price_list_update, name='auto_pl_update'),
    url(r'^auto_price_list/save/id=(?P<auto_pl_id>\d+)/$', views.auto_price_list_save, name='auto_pl_save'),
    url(r'^auto_price_list_supplier/save/auto_pl_id=(?P<auto_pl_id>\d+)/$', views.auto_pl_supplier_save, name='auto_pl_sup_save'),
    url(r'^auto_price_list_supplier/create/auto_pl_id=(?P<auto_pl_id>\d+)/$', views.auto_pl_supplier_addition, name='auto_pl_sup_create'),
    url(r'^auto_price_list/matrix/$', views.auto_pl_matrix, name='auto_pl_matrix'),
    url(r'^auto_rmp_supplier/save/id=(?P<rmp_supply_id>\d+)/$', views.auto_rmp_supplier_save, name='auto_rmp_sup_save'),
    url(r'^auto_rmp_supplier/detail/auto_rmp_id=(?P<auto_rmp_id>\d+)/type=(?P<sup_type>\w+)/sup_id=(?P<pl_sup_id>\d+)/$', views.auto_rmp_supplier_detail, name='auto_rmp_sup_detail'),
    url(r'^auto_rmp/create/$', views.auto_rmp_create, name='auto_rmp_create'),
    url(r'^auto_rmp/detail/id=(?P<auto_rmp_id>\d+)/$', views.auto_rmp_detail, name='auto_rmp_detail'),
    url(r'^auto_rmp/save/$', views.auto_rmp_save, name='auto_rmp_save'),
    url(r'^coa_and_group/index/$', views.coa_and_group_index, name='coa_and_group_index'),
    url(r'^coa_group/create/parent_coa_group_id=(?P<parent_coa_group_id>\d+)/$', views.coa_group_create, name='coa_group_create'),
    url(r'^coa_group/detail/id=(?P<coa_group_id>\d+)/$', views.coa_group_detail, name='coa_group_detail'),
    url(r'^coa/create/coa_group_id=(?P<coa_group_id>\d+)/$', views.coa_create, name='coa_create'),
    url(r'^coa/detail/id=(?P<coa_id>\d+)/$', views.coa_detail, name='coa_detail'),
    url(r'^coa/save/$', views.coa_save, name='coa_save'),
    url(r'^coa/index/coa_group_id=(?P<coa_group_id>\d+)/$', views.coa_index, name='coa_index'),
    url(r'^confirmation_page/$', views.confirmation_page, name='confirmation'),
    url(r'^constants/create/$', views.constants_create, name='auto_rmp_create'),
    url(r'^constants/detail/id=(?P<constants_id>\d+)/$', views.constants_detail, name='constants_detail'),
    url(r'^constants/save/$', views.constants_save, name='constants_save'),
    url(r'^crm_auto_pl_mgmt/$', views.crm_auto_pl_mgmt, name='crm_auto_pl_mgmt'),
    url(r'^crm_bom_crud/action_type=(?P<action_type>\w+)/table_name=(?P<table_name>\w+)/$', views.crm_bom_crud, name='crm_bom_crud'),
    url(r'^crm_derivative_crud/action_type=(?P<action_type>\w+)/table_name=(?P<table_name>\w+)/$', views.crm_derivative_crud, name='crm_derivative_crud'),
    url(r'^cur_stock/$', views.cur_stock, name='cur_stock'),
    #url(r'^home/$', views.home, name='home'),
    url(r'^cluster_pl/id=(?P<quote_pl_id>\d+)/$', views.cluster_pl_detail, name='cluster_pl'),
    url(r'^crm_pl_index/$', views.crm_pl_index, name='crm_pl_index'),
    url(r'^crm_pl_delete/id=(?P<crm_pl_id>\d+)/$', views.crm_pl_delete, name='crm_pl_delete'),
    url(r'^home_view/index/dept=(?P<dept_id>\d+)/$', views.home_view, name='home_view'),
    url(r'^inventory_journal/delete/id=(?P<inv_jour_id>\d+)/$', views.inv_jour_delete, name='inv_jour_delete'),
    url(r'^inventroy_journal/bulk_create/$', views.inv_jour_bulk_create, name='inv_jour_bulk_create'),
    url(r'^inventroy_journal/add/$', views.inv_jour_add, name='inv_journal_add'),
    url(r'^item_master/create/$', views.item_master_create, name='item_master_create'),
    url(r'^item_master/detail/id=(?P<item_master_id>\d+)/$', views.item_master_detail, name='item_master_detail'),
    url(r'^item_master/save/$', views.item_master_save, name='item_master_save'),
    url(r'^item_master/index/$', views.item_master_index, name='item_master_index'),
    url(r'^job_shop_order_preview/detail/id=(?P<tref_id>\d+)/$', views.job_shop_order_preview, name='job_shop_order_preview'),
    url(r'^job_shop_order/detail/id=(?P<tref_id>\d+)/$', views.job_shop_order, name='job_shop_order'),
    url(r'^login/$', views.login_page, name='login'),
    url(r'^login_authenticate/$', views.login_authenticate, name='login_authenticate'),
    url(r'^doc_list/tab_name=(?P<tab_name>\w+)/tab_id=(?P<tab_id>\d+)/doc_type_id=(?P<doc_type_id>\d+)/$', views.doc_list, name='doc_list'),
    url(r'^doc_delete/id=(?P<doc_id>\d+)/$', views.doc_delete, name='doc_delete'),
    url(r'^pdf_view/$', views.pdf_view, name='pdf_view'),
    url(r'^pdf_response/$', views.pdf_response, name='pdf_response'),
    url(r'^mrs/detail/id=(?P<tref_id>\d+)/$', views.mrs_preview, name='mrs_preview'),
    url(r'^new_quote_pl/id=(?P<quote_pl_id>\d+)/$', views.new_quote_pl_detail, name='new_quote_pl'),
    url(r'^packing_list/id=(?P<tref_id>\d+)/$', views.packing_list, name='packing_list'),
    url(r'^production_auto_plan/id=(?P<tref_id>\d+)/$', views.production_auto_plan, name='production_auto_plan'),
    url(r'^price_report/$', views.price_report, name='price_report'),
    url(r'^quote_import/$', views.quote_import, name='quote_import'),
    url(r'^quote_save/id=(?P<quotation_id>\d+)/$', views.quotation_save, name='quote_save'),
    url(r'^quote_redirect/id=(?P<quotation_id>\d+)/$', views.quote_redirect, name='quote_redirect'),
    url(r'^quote_write_back/id=(?P<quotation_id>\d+)/$', views.quote_write_back, name='quote_write_back'),
    url(r'^shipment/create/$', views.shipment_create, name='shipment_create'),
    url(r'^transaction_report/$', views.transaction_report, name='transaction_report'),
    url(r'^transaction_ref/index/ttype=(?P<ttype_id>\d+)/$', views.tref_index, name='tref_index'),
    url(r'^transaction_ref/detail/id=(?P<tref_id>\d+)/$', views.tref_detail, name='tref_detail'),
    url(r'^transaction_ref/detail_popup/id=(?P<tref_id>\d+)/$', views.tref_detail_popup, name='tref_detail_popup'),
    url(r'^transaction_ref/create/ttype=(?P<ttype_id>\d+)/$', views.tref_create, name='tref_create'),
    url(r'^transaction_ref/cons_dwg_tref/$', views.cons_dwg_tref, name='cons_dwg_tpl'),
    url(r'^transaction_ref/tpl_consolidation/$', views.tpl_consolidation, name='tpl_consolidation'),
    url(r'^test_response/$', views.test_http, name='test_response'),
    url(r'^test_rig/$', views.test_rig, name='test_rig'),
    url(r'^tpl_auto_plan/id=(?P<tref_id>\d+)/$', views.tpl_auto_plan, name='tpl_auto_plan'),
    url(r'^transaction_ref/save/$', views.tref_save, name='tref_save'),
    url(r'^tree_test/$', views.tree_test, name='tree_test'),
    url(r'^vendor_pl/detail/$', views.vendor_pl_detail, name='vendor_pl_detail'),
    url(r'^vendor_pl/index/$', views.vendor_pl_index, name='vendor_pl_index'),
    url(r'^wc_vendor_rmp_supplier/detail/auto_rmp_id=(?P<auto_rmp_id>\d+)/type=(?P<sup_type>\w+)/sup_id=(?P<pl_sup_id>\d+)/$', views.wc_vendor_rmp_supplier_detail, name='wc_vendor_rmp_supplier_detail'),
    url(r'^wc_pl/detail/$', views.wc_pl_detail, name='wc_pl_detail'),
    url(r'^wc_pl/index/$', views.wc_pl_index, name='wc_pl_index'),
    url(r'web_gl_test/$', views.web_gl_test, name='web_gl_test'),

    )

'''
urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)'''